### ISSUE TITLE
拉库提示网络错误

### ISSUE THREAD

**Issue by kid-oh** [KingRan/JD-Scripts#13]
无论是国内机还是国外的拉库命令都会提示网络错误，用的是腾讯云，只有删除青龙里的ghproxy才可以拉库成功，不过删除后其他一些库就拉不了了.......

**Comment by KingRan** [comment]
无法挂代理的可以修改青龙 config.sh 文件中的GithubProxyUrl参数为：
https://pd.zwc365.com/ 或&nbsp;
https://pd.zwc365.com/cfworker/ 临时解决。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 晚上10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [KingRan/JD-Scripts] 拉库提示网络错误 (Issue #13)





 
无论是国内机还是国外的拉库命令都会提示网络错误，用的是腾讯云，只有删除青龙里的ghproxy才可以拉库成功，不过删除后其他一些库就拉不了了.......
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kid-oh** [comment]
可以了 谢谢！其他库也可以拉了
